let AXES_ITEMS = [
  {
    KEY: 'AXES_HAND AXE',
    Name: 'Hand Axe',
    'Cost ep': '30',
    Weight: '40',
    Size: '35',
    Range: '15',
    'Speed, Missle': '3',
    'Speed, Melee': '3',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '5',
    'STN, 2H': '3.25',
    STMOD: '1.1',
    'CDN, 1H': '11',
    'CDN, 2H': '8.25',
    CDMOD: '0.85',
    'Damage Dice': '2d6+9',
    'Dividing Die': '8',
    'Real min': '1.38',
    'Max Dam': '21',
    'Av Dam': '11.19',
  },
  {
    KEY: 'AXES_HAND SICKLE',
    Name: 'Hand Sickle',
    'Cost ep': '44',
    Weight: '60',
    Size: '24',
    Range: '20',
    'Speed, Missle': '5',
    'Speed, Melee': '4',
    'Speed, Readied': '4',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '7',
    'STN, 2H': '5.25',
    STMOD: '1.3',
    'CDN, 1H': '16',
    'CDN, 2H': '12',
    CDMOD: '0.8',
    'Damage Dice': '2d6+12',
    'Dividing Die': '8',
    'Real min': '1.75',
    'Max Dam': '24',
    'Av Dam': '12.88',
  },
  {
    KEY: 'AXES_SICKLE, MEDIUM',
    Name: 'Sickle, Medium',
    'Cost ep': '80',
    Weight: '130',
    Size: '52',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '8',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '13',
    'STN, 2H': '9.75',
    STMOD: '2.1',
    'CDN, 1H': '10',
    'CDN, 2H': '7.5',
    CDMOD: '0.55',
    'Damage Dice': 'd10+14',
    'Dividing Die': '6',
    'Real min': '2.50',
    'Max Dam': '24',
    'Av Dam': '13.25',
  },
  {
    KEY: 'AXES_FRANSISCA',
    Name: 'Fransisca',
    'Cost ep': '80',
    Weight: '75',
    Size: '32',
    Range: '30',
    'Speed, Missle': '5',
    'Speed, Melee': '6',
    'Speed, Readied': '6',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '10',
    'STN, 2H': '6.75',
    STMOD: '1.45',
    'CDN, 1H': '14',
    'CDN, 2H': '11.25',
    CDMOD: '0.55',
    'Damage Dice': '4d4+9',
    'Dividing Die': '8',
    'Real min': '1.63',
    'Max Dam': '25',
    'Av Dam': '13.31',
  },
  {
    KEY: 'AXES_BHUJ',
    Name: 'Bhuj',
    'Cost ep': '140',
    Weight: '160',
    Size: '40',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '9',
    'Speed, Readied': '9',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '15',
    'STN, 2H': '11.25',
    STMOD: '2.5',
    'CDN, 1H': '10',
    'CDN, 2H': '7.5',
    CDMOD: '0.6',
    'Damage Dice': '2d6+14',
    'Dividing Die': '6',
    'Real min': '2.67',
    'Max Dam': '26',
    'Av Dam': '14.33',
  },
  {
    KEY: 'AXES_CLAWED HAMMER',
    Name: 'Clawed Hammer',
    'Cost ep': '110',
    Weight: '120',
    Size: '36',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '5',
    'Speed, Readied': '5',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '13',
    'STN, 2H': '9',
    STMOD: '2.2',
    'CDN, 1H': '13',
    'CDN, 2H': '9',
    CDMOD: '.75',
    'Damage Dice': '15+2d6',
    'Dividing Die': '6',
    'Real min': '2.83',
    'Max Dam': '27',
    'Av Dam': ' ',
  },
  {
    KEY: 'AXES_BROADAXE',
    Name: 'BroadAxe',
    'Cost ep': '190',
    Weight: '150',
    Size: '36',
    Range: '10',
    'Speed, Missle': '8',
    'Speed, Melee': '7',
    'Speed, Readied': '6',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '17',
    'STN, 2H': '12.75',
    STMOD: '2.72',
    'CDN, 1H': '10',
    'CDN, 2H': '7.5',
    CDMOD: '0.6',
    'Damage Dice': 'd10+18',
    'Dividing Die': '6',
    'Real min': '3.17',
    'Max Dam': '28',
    'Av Dam': '15.58',
  },
  {
    KEY: 'AXES_SCYTHE',
    Name: 'Scythe',
    'Cost ep': '100',
    Weight: '155',
    Size: '70',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '9',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '17',
    'STN, 2H': '12.75',
    STMOD: '2.7',
    'CDN, 1H': '12',
    'CDN, 2H': '9',
    CDMOD: '0.7',
    'Damage Dice': 'd10+18',
    'Dividing Die': '6',
    'Real min': '3.17',
    'Max Dam': '28',
    'Av Dam': '15.58',
  },
  {
    KEY: 'AXES_BULLOVA',
    Name: 'Bullova',
    'Cost ep': '180',
    Weight: '200',
    Size: '42',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '9',
    'Speed, Readied': '6',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '20',
    'STN, 2H': '15',
    STMOD: '3.2',
    'CDN, 1H': '7',
    'CDN, 2H': '5.25',
    CDMOD: '0.9',
    'Damage Dice': 'd10+18',
    'Dividing Die': '5',
    'Real min': '3.80',
    'Max Dam': '28',
    'Av Dam': '15.90',
  },
  {
    KEY: 'AXES_GREAT AXE',
    Name: 'Great Axe',
    'Cost ep': '230',
    Weight: '190',
    Size: '36',
    Range: '2',
    'Speed, Missle': '10',
    'Speed, Melee': '10',
    'Speed, Readied': '6',
    Protection: '3',
    'Threat Range': '2',
    'STN, 1H': '18',
    'STN, 2H': '13.5',
    STMOD: '3.4',
    'CDN, 1H': '10',
    'CDN, 2H': '7.5',
    CDMOD: '0.52',
    'Damage Dice': 'd12+19',
    'Dividing Die': '5',
    'Real min': '4.00',
    'Max Dam': '31',
    'Av Dam': '17.50',
  },
  {
    KEY: 'AXES_WIDOWMAKER',
    Name: 'WidowMaker',
    'Cost ep': '420',
    Weight: '230',
    Size: '60',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '11',
    'Speed, Readied': '6',
    Protection: '0',
    'Threat Range': '2',
    'STN, 1H': '22',
    'STN, 2H': '17',
    STMOD: '3.5',
    'CDN, 1H': '14',
    'CDN, 2H': '11',
    CDMOD: '0.55',
    'Damage Dice': '2d8+18',
    'Dividing Die': '5',
    'Real min': '4.00',
    'Max Dam': '34',
    'Av Dam': '19.00',
  },
  {
    KEY: 'AXES_BEC DI CORBIN',
    Name: 'Bec Di Corbin',
    'Cost ep': '310',
    Weight: '185',
    Size: '65',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '10',
    'Speed, Readied': '9',
    Protection: '0',
    'Threat Range': '2',
    'STN, 1H': '19',
    'STN, 2H': '14.25',
    STMOD: '3.5',
    'CDN, 1H': '16',
    'CDN, 2H': '12',
    CDMOD: '0.7',
    'Damage Dice': '3d6+17',
    'Dividing Die': '5',
    'Real min': '4.00',
    'Max Dam': '35',
    'Av Dam': '19.50',
  },
  {
    KEY: 'AXES_DOUBLE BLADED BROADAXE',
    Name: 'Double Bladed Broadaxe',
    'Cost ep': '250',
    Weight: '230',
    Size: '55',
    Range: '4',
    'Speed, Missle': '8',
    'Speed, Melee': '12',
    'Speed, Readied': '10',
    Protection: '0',
    'Threat Range': '3',
    'STN, 1H': '23',
    'STN, 2H': '17.25',
    STMOD: '3.7',
    'CDN, 1H': '15',
    'CDN, 2H': '11.25',
    CDMOD: '0.8',
    'Damage Dice': '3d6+19',
    'Dividing Die': '4',
    'Real min': '5.50',
    'Max Dam': '37',
    'Av Dam': '21.25',
  },
];

let BLUNT_ITEMS = [
  {
    KEY: 'BLUNT_HAND',
    Name: 'Hand',
    'Cost ep': '0',
    Weight: '0',
    Size: '0',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '2',
    'Speed, Readied': '1',
    Protection: '0',
    'Threat Range': '-3',
    'STN, 1H': '15',
    'STN, 2H': '0',
    STMOD: '2',
    'CDN, 1H': '15',
    'CDN, 2H': '0',
    CDMOD: '1',
    'Damage Dice': 'd6+2',
    'Dividing Die': '6',
    'Real min': '0.50',
    'Max Dam': '8',
    'Av Dam': '4.25',
  },
  {
    KEY: 'BLUNT_CLUB',
    Name: 'club',
    'Cost ep': '14',
    Weight: '60',
    Size: '24',
    Range: '25',
    'Speed, Missle': '6',
    'Speed, Melee': '5',
    'Speed, Readied': '4',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '10',
    'STN, 2H': '7.5',
    STMOD: '1.7',
    'CDN, 1H': '11',
    'CDN, 2H': '7.8',
    CDMOD: '0.8',
    'Damage Dice': '1d8+9',
    'Dividing Die': '8',
    'Real min': '1.25',
    'Max Dam': '17',
    'Av Dam': '9.13',
  },
  {
    KEY: 'BLUNT_MITRE',
    Name: 'Mitre',
    'Cost ep': '100',
    Weight: '90',
    Size: '33',
    Range: '28',
    'Speed, Missle': '5',
    'Speed, Melee': '5',
    'Speed, Readied': '4',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '10',
    'STN, 2H': '7.5',
    STMOD: '1.7',
    'CDN, 1H': '6',
    'CDN, 2H': '4.5',
    CDMOD: '0.45',
    'Damage Dice': '2d4+10',
    'Dividing Die': '6',
    'Real min': '2.00',
    'Max Dam': '18',
    'Av Dam': '10.00',
  },
  {
    KEY: 'BLUNT_FLANGED MACE',
    Name: 'Flanged Mace',
    'Cost ep': '120',
    Weight: '100',
    Size: '28',
    Range: '30',
    'Speed, Missle': '7',
    'Speed, Melee': '5',
    'Speed, Readied': '4',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '13',
    'STN, 2H': '9',
    STMOD: '2.3',
    'CDN, 1H': '7',
    'CDN, 2H': '5.25',
    CDMOD: '.55',
    'Damage Dice': '2d4+11',
    'Dividing Die': '6',
    'Real min': '2.16',
    'Max Dam': '19',
    'Av Dam': ' ',
  },
  {
    KEY: 'BLUNT_LIGHT FLAIL',
    Name: 'Light Flail',
    'Cost ep': '140',
    Weight: '130',
    Size: '35',
    Range: '30',
    'Speed, Missle': '7',
    'Speed, Melee': '6',
    'Speed, Readied': '6',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '15',
    'STN, 2H': '9.75',
    STMOD: '2.55',
    'CDN, 1H': '13',
    'CDN, 2H': '9.75',
    CDMOD: '0.6',
    'Damage Dice': '2d6+10',
    'Dividing Die': '6',
    'Real min': '2.00',
    'Max Dam': '22',
    'Av Dam': '12.00',
  },
  {
    KEY: 'BLUNT_HEAVY FLAIL',
    Name: 'Heavy Flail',
    'Cost ep': '150',
    Weight: '190',
    Size: '40',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '7',
    'Speed, Readied': '7',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '17',
    'STN, 2H': '12.75',
    STMOD: '2.9',
    'CDN, 1H': '14',
    'CDN, 2H': '10.5',
    CDMOD: '0.65',
    'Damage Dice': '2d8+14',
    'Dividing Die': '5',
    'Real min': '3.00',
    'Max Dam': '29',
    'Av Dam': '16.00',
  },
  {
    KEY: 'BLUNT_MORNINGSTAR',
    Name: 'Morningstar',
    'Cost ep': '180',
    Weight: '130',
    Size: '41',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '8',
    'Speed, Readied': '8',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '17',
    'STN, 2H': '12.75',
    STMOD: '2.75',
    'CDN, 1H': '14',
    'CDN, 2H': '10.5',
    CDMOD: '0.64',
    'Damage Dice': '2d8+14',
    'Dividing Die': '5',
    'Real min': '3.20',
    'Max Dam': '30',
    'Av Dam': '16.60',
  },
  {
    KEY: 'BLUNT_HEAVY MACE',
    Name: 'Heavy Mace',
    'Cost ep': '200',
    Weight: '300',
    Size: '50',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '11',
    'Speed, Readied': '10',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '20',
    'STN, 2H': '15',
    STMOD: '3.5',
    'CDN, 1H': '11',
    'CDN, 2H': '8.25',
    CDMOD: '0.5',
    'Damage Dice': '2d10+15',
    'Dividing Die': '4',
    'Real min': '4.25',
    'Max Dam': '35',
    'Av Dam': '19.63',
  },
  {
    KEY: 'BLUNT_WAR HAMMER',
    Name: 'War Hammer',
    'Cost ep': '400',
    Weight: '220',
    Size: '33',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '8',
    'Speed, Readied': '8',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '23',
    'STN, 2H': '17.25',
    STMOD: '3.8',
    'CDN, 1H': '13',
    'CDN, 2H': '9.75',
    CDMOD: '0.65',
    'Damage Dice': '3d6+20',
    'Dividing Die': '4',
    'Real min': '5.75',
    'Max Dam': '38',
    'Av Dam': '21.88',
  },
];

let BOWS_ITEMS = [
  {
    KEY: 'BOWS_LIGHT HORSEBOW',
    Name: 'Light HorseBow',
    'Cost ep': '80',
    Weight: '50',
    Size: '36',
    Range: '75',
    'Speed, Missle': '2',
    'Speed, Melee': '0',
    'Speed, Readied': '2',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '0',
    'STN, 2H': '6.75',
    STMOD: '0.45',
    'CDN, 1H': '0',
    'CDN, 2H': '10',
    CDMOD: '1.3',
    'Damage Dice': 'd12+11',
    'Dividing Die': '10',
    'Real min': '1.20',
    'Max Dam': '23',
    'Av Dam': '12.10',
  },
  {
    KEY: 'BOWS_LIGHT LONGBOW',
    Name: 'Light LongBow',
    'Cost ep': '100',
    Weight: '80',
    Size: '37',
    Range: '100',
    'Speed, Missle': '4',
    'Speed, Melee': '0',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '0',
    'STN, 2H': '11',
    STMOD: '0.5',
    'CDN, 1H': '0',
    'CDN, 2H': '11',
    CDMOD: '1.35',
    'Damage Dice': '2d8+11',
    'Dividing Die': '10',
    'Real min': '1.30',
    'Max Dam': '27',
    'Av Dam': '14.15',
  },
  {
    KEY: 'BOWS_LIGHT COMPOUND BOW',
    Name: 'Light Compound Bow',
    'Cost ep': '160',
    Weight: '75',
    Size: '38',
    Range: '100',
    'Speed, Missle': '3',
    'Speed, Melee': '0',
    'Speed, Readied': '2',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '0',
    'STN, 2H': '10',
    STMOD: '0.65',
    'CDN, 1H': '0',
    'CDN, 2H': '10',
    CDMOD: '1.56',
    'Damage Dice': '1d8+1d6+13',
    'Dividing Die': '10',
    'Real min': '1.50',
    'Max Dam': '27',
    'Av Dam': '14.25',
  },
  {
    KEY: 'BOWS_MEDIUM LONGBOW',
    Name: 'Medium LongBow',
    'Cost ep': '150',
    Weight: '100',
    Size: '40',
    Range: '130',
    'Speed, Missle': '5',
    'Speed, Melee': '0',
    'Speed, Readied': '4',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '0',
    'STN, 2H': '11',
    STMOD: '0.7',
    'CDN, 1H': '0',
    'CDN, 2H': '13',
    CDMOD: '1.56',
    'Damage Dice': '2d8+13',
    'Dividing Die': '8',
    'Real min': '1.88',
    'Max Dam': '29',
    'Av Dam': '15.44',
  },
  {
    KEY: 'BOWS_HEAVY COMPOUND BOW',
    Name: 'Heavy Compound bow',
    'Cost ep': '180',
    Weight: '125',
    Size: '40',
    Range: '125',
    'Speed, Missle': '4',
    'Speed, Melee': '0',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '0',
    'STN, 2H': '11.3',
    STMOD: '0.75',
    'CDN, 1H': '0',
    'CDN, 2H': '12.75',
    CDMOD: '1.75',
    'Damage Dice': '1d8+1d10+14',
    'Dividing Die': '8',
    'Real min': '2.25',
    'Max Dam': '32',
    'Av Dam': '17.13',
  },
  {
    KEY: 'BOWS_VHEAVY COMPOSITE BOW',
    Name: 'Vheavy Composite Bow',
    'Cost ep': '380',
    Weight: '150',
    Size: '48',
    Range: '160',
    'Speed, Missle': '5',
    'Speed, Melee': '0',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '0',
    'STN, 2H': '14',
    STMOD: '0.85',
    'CDN, 1H': '0',
    'CDN, 2H': '14',
    CDMOD: '2',
    'Damage Dice': '3d6+16',
    'Dividing Die': '8',
    'Real min': '2.38',
    'Max Dam': '34',
    'Av Dam': '18.19',
  },
  {
    KEY: 'BOWS_VERY HEAVY LONGBOW',
    Name: 'Very Heavy Longbow',
    'Cost ep': '380',
    Weight: '250',
    Size: '55',
    Range: '220',
    'Speed, Missle': '8',
    'Speed, Melee': '0',
    'Speed, Readied': '7',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '0',
    'STN, 2H': '16',
    STMOD: '1',
    'CDN, 1H': '0',
    'CDN, 2H': '18',
    CDMOD: '1.8',
    'Damage Dice': '2d10+18',
    'Dividing Die': '6',
    'Real min': '3.33',
    'Max Dam': '38',
    'Av Dam': '20.67',
  },
];

let CROSSBOWS_ITEMS = [
  {
    KEY: 'CROSSBOWS_HAND CROSSBOW',
    Name: 'Hand CrossBow',
    'Cost ep': '220',
    Weight: '30',
    Size: '18',
    Range: '40',
    'Speed, Missle': '6',
    'Speed, Melee': '0',
    'Speed, Readied': '2',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '9',
    'STN, 2H': '0',
    STMOD: '0.45',
    'CDN, 1H': '13',
    'CDN, 2H': '0',
    CDMOD: '1.4',
    'Damage Dice': '2d8+9',
    'Dividing Die': '8',
    'Real min': '1.38',
    'Max Dam': '27',
    'Av Dam': '14.19',
  },
  {
    KEY: 'CROSSBOWS_CRANQUIN',
    Name: 'Cranquin',
    'Cost ep': '620',
    Weight: '250',
    Size: '45',
    Range: '140',
    'Speed, Missle': '11',
    'Speed, Melee': '0',
    'Speed, Readied': '5',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '0',
    'STN, 2H': '16',
    STMOD: '0.8',
    'CDN, 1H': '0',
    'CDN, 2H': '13',
    CDMOD: '1.3',
    'Damage Dice': '2d10+18',
    'Dividing Die': '6',
    'Real min': '3.33',
    'Max Dam': '38',
    'Av Dam': '20.67',
  },
  {
    KEY: 'CROSSBOWS_ARBELEST',
    Name: 'Arbelest',
    'Cost ep': '900',
    Weight: '350',
    Size: '55',
    Range: '140',
    'Speed, Missle': '14',
    'Speed, Melee': '0',
    'Speed, Readied': '5',
    Protection: '0',
    'Threat Range': '2',
    'STN, 1H': '0',
    'STN, 2H': '18',
    STMOD: '1.1',
    'CDN, 1H': '0',
    'CDN, 2H': '14',
    CDMOD: '1.5',
    'Damage Dice': '2d6+1d8+23',
    'Dividing Die': '6',
    'Real min': '4.33',
    'Max Dam': '43',
    'Av Dam': '23.67',
  },
];

let ARROWS_ITEMS = [
  {
    KEY: 'ARROWS_BOLT, CROSSBOW',
    Name: 'Bolt, Crossbow',
    'Cost ep': '1',
    Weight: '1',
    Size: '14',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '0',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '0',
    'STN, 2H': '0',
    STMOD: '0',
    'CDN, 1H': '0',
    'CDN, 2H': '0',
    CDMOD: '0',
    'Damage Dice': '1d10',
    'Dividing Die': '6',
    'Real min': '0.17',
    'Max Dam': '10',
    'Av Dam': '5.08',
  },
  {
    KEY: 'ARROWS_BLUNT TIP ARROW (.3 REAL DAM)',
    Name: 'Blunt Tip Arrow (.3 real dam)',
    'Cost ep': '2',
    Weight: '5',
    Size: '24',
    Range: '-10',
    'Speed, Missle': '1',
    'Speed, Melee': '0',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '0',
    'STN, 2H': '0',
    STMOD: '0',
    'CDN, 1H': '0',
    'CDN, 2H': '0',
    CDMOD: '0',
    'Damage Dice': '1d10',
    'Dividing Die': '6',
    'Real min': '0.17',
    'Max Dam': '10',
    'Av Dam': '5.08',
  },
  {
    KEY: 'ARROWS_NORMAL ARROW',
    Name: 'Normal Arrow',
    'Cost ep': '0.5',
    Weight: '2',
    Size: '26',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '0',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '0',
    'STN, 2H': '0',
    STMOD: '0',
    'CDN, 1H': '0',
    'CDN, 2H': '0',
    CDMOD: '0',
    'Damage Dice': '2d6',
    'Dividing Die': '6',
    'Real min': '0.33',
    'Max Dam': '12',
    'Av Dam': '6.17',
  },
  {
    KEY: 'ARROWS_HOLLOW VEIN ARROW',
    Name: 'Hollow vein arrow',
    'Cost ep': '10',
    Weight: '4',
    Size: '24',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '0',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '0',
    'STN, 2H': '0',
    STMOD: '0',
    'CDN, 1H': '0',
    'CDN, 2H': '0',
    CDMOD: '0',
    'Damage Dice': '2d6',
    'Dividing Die': '6',
    'Real min': '0.33',
    'Max Dam': '12',
    'Av Dam': '6.17',
  },
  {
    KEY: 'ARROWS_HUNTING ARROW',
    Name: 'Hunting Arrow',
    'Cost ep': '1.5',
    Weight: '3',
    Size: '36',
    Range: '20',
    'Speed, Missle': '1',
    'Speed, Melee': '0',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '0',
    'STN, 2H': '0',
    STMOD: '0',
    'CDN, 1H': '0',
    'CDN, 2H': '0',
    CDMOD: '0',
    'Damage Dice': '2d6+1',
    'Dividing Die': '6',
    'Real min': '0.50',
    'Max Dam': '13',
    'Av Dam': '6.75',
  },
  {
    KEY: 'ARROWS_HEAVY HEAD SERRATED ARROW',
    Name: 'Heavy Head serrated Arrow',
    'Cost ep': '16',
    Weight: '4',
    Size: '30',
    Range: '-15',
    'Speed, Missle': '1',
    'Speed, Melee': '0',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '0',
    'STN, 2H': '0',
    STMOD: '0',
    'CDN, 1H': '0',
    'CDN, 2H': '0',
    CDMOD: '0',
    'Damage Dice': '4d4',
    'Dividing Die': '6',
    'Real min': '0.67',
    'Max Dam': '16',
    'Av Dam': '8.33',
  },
];

let CURVED_SWORDS_ITEMS = [
  {
    KEY: 'CURVED_SWORDS_SHORT SABRE',
    Name: 'Short Sabre',
    'Cost ep': '70',
    Weight: '35',
    Size: '25',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '3',
    'Speed, Readied': '3',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '11',
    'STN, 2H': '8.25',
    STMOD: '8.25',
    'CDN, 1H': '10',
    'CDN, 2H': '7.5',
    CDMOD: '0.71',
    'Damage Dice': '1d8+11',
    'Dividing Die': '8',
    'Real min': '1.50',
    'Max Dam': '19',
    'Av Dam': '10.25',
  },
  {
    KEY: 'CURVED_SWORDS_MANOPLE',
    Name: 'Manople',
    'Cost ep': '80',
    Weight: '30',
    Size: '33',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '5',
    'Speed, Readied': '5',
    Protection: '3',
    'Threat Range': '-1',
    'STN, 1H': '12',
    'STN, 2H': '9',
    STMOD: '9',
    'CDN, 1H': '9',
    'CDN, 2H': '6.75',
    CDMOD: '0.85',
    'Damage Dice': '1d8+11',
    'Dividing Die': '8',
    'Real min': '1.50',
    'Max Dam': '19',
    'Av Dam': '10.25',
  },
  {
    KEY: 'CURVED_SWORDS_SABRE',
    Name: 'Sabre',
    'Cost ep': '84',
    Weight: '60',
    Size: '36',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '4',
    'Speed, Readied': '4',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '12',
    'STN, 2H': '9',
    STMOD: '9',
    'CDN, 1H': '12',
    'CDN, 2H': '9',
    CDMOD: '0.86',
    'Damage Dice': '1d12+10',
    'Dividing Die': '6',
    'Real min': '2.17',
    'Max Dam': '22',
    'Av Dam': '12.08',
  },
  {
    KEY: 'CURVED_SWORDS_SCIMITAR',
    Name: 'Scimitar',
    'Cost ep': '100',
    Weight: '100',
    Size: '39',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '5',
    'Speed, Readied': '5',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '14',
    'STN, 2H': '10.5',
    STMOD: '10.5',
    'CDN, 1H': '13',
    'CDN, 2H': '9.75',
    CDMOD: '0.95',
    'Damage Dice': '1d8+1d6+11',
    'Dividing Die': '6',
    'Real min': '2.17',
    'Max Dam': '25',
    'Av Dam': '13.58',
  },
  {
    KEY: 'CURVED_SWORDS_FALCHION',
    Name: 'Falchion',
    'Cost ep': '130',
    Weight: '110',
    Size: '46',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '6',
    'Speed, Readied': '6',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '16',
    'STN, 2H': '12',
    STMOD: '12',
    'CDN, 1H': '15',
    'CDN, 2H': '11.25',
    CDMOD: '1.07',
    'Damage Dice': '2d4+1d8+10',
    'Dividing Die': '6',
    'Real min': '2.17',
    'Max Dam': '26',
    'Av Dam': '14.08',
  },
  {
    KEY: 'CURVED_SWORDS_GREAT SHAMSHEER',
    Name: 'Great Shamsheer',
    'Cost ep': '180',
    Weight: '130',
    Size: '60',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '7',
    'Speed, Readied': '7',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '19',
    'STN, 2H': '14.25',
    STMOD: '14.25',
    'CDN, 1H': '18',
    'CDN, 2H': '13.5',
    CDMOD: '1.34',
    'Damage Dice': '1d8+1d6+16',
    'Dividing Die': '6',
    'Real min': '3.00',
    'Max Dam': '30',
    'Av Dam': '16.50',
  },
  {
    KEY: 'CURVED_SWORDS_WHIZZLE (2 BLADE SWORD)',
    Name: 'Whizzle (2 blade sword)',
    'Cost ep': '380',
    Weight: '165',
    Size: '72',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '7',
    'Speed, Readied': '7',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '0',
    'STN, 2H': '14',
    STMOD: '14',
    'CDN, 1H': '0',
    'CDN, 2H': '15',
    CDMOD: '1.75',
    'Damage Dice': '1d8+1d10+14',
    'Dividing Die': '6',
    'Real min': '2.67',
    'Max Dam': '32',
    'Av Dam': '17.33',
  },
  {
    KEY: 'CURVED_SWORDS_GRAND SHAMSHEER',
    Name: 'Grand Shamsheer',
    'Cost ep': '340',
    Weight: '160',
    Size: '70',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '10',
    'Speed, Readied': '10',
    Protection: '1',
    'Threat Range': '1',
    'STN, 1H': '21',
    'STN, 2H': '15.75',
    STMOD: '15.75',
    'CDN, 1H': '20',
    'CDN, 2H': '15',
    CDMOD: '1.45',
    'Damage Dice': '2d8+19',
    'Dividing Die': '5',
    'Real min': '4.20',
    'Max Dam': '35',
    'Av Dam': '19.60',
  },
];

let DAGGERS_ITEMS = [
  {
    KEY: 'DAGGERS_STILLETTO',
    Name: 'Stilletto',
    'Cost ep': '28',
    Weight: '12',
    Size: '6',
    Range: '9',
    'Speed, Missle': '1',
    'Speed, Melee': '2',
    'Speed, Readied': '1',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '2',
    'STN, 2H': '1',
    STMOD: '0.25',
    'CDN, 1H': '5',
    'CDN, 2H': '3.75',
    CDMOD: '0.35',
    'Damage Dice': '2d6+1',
    'Dividing Die': '10',
    'Real min': '0.30',
    'Max Dam': '13',
    'Av Dam': '6.65',
  },
  {
    KEY: 'DAGGERS_MAIN GAUCHE',
    Name: 'Main Gauche',
    'Cost ep': '70',
    Weight: '30',
    Size: '16',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '4',
    'Speed, Readied': '4',
    Protection: '3',
    'Threat Range': '-1',
    'STN, 1H': '6',
    'STN, 2H': '4.5',
    STMOD: '0.78',
    'CDN, 1H': '10',
    'CDN, 2H': '7.5',
    CDMOD: '0.55',
    'Damage Dice': '2d6+2',
    'Dividing Die': '10',
    'Real min': '0.40',
    'Max Dam': '14',
    'Av Dam': '7.20',
  },
  {
    KEY: 'DAGGERS_MISERICORDE',
    Name: 'Misericorde',
    'Cost ep': '48',
    Weight: '14',
    Size: '13',
    Range: '13',
    'Speed, Missle': '3',
    'Speed, Melee': '3',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '3',
    'STN, 2H': '2.5',
    STMOD: '0.4',
    'CDN, 1H': '7',
    'CDN, 2H': '5.25',
    CDMOD: '0.4',
    'Damage Dice': '2d4+9',
    'Dividing Die': '10',
    'Real min': '1.10',
    'Max Dam': '17',
    'Av Dam': '9.05',
  },
  {
    KEY: 'DAGGERS_DIRK',
    Name: 'Dirk',
    'Cost ep': '38',
    Weight: '15',
    Size: '9',
    Range: '12',
    'Speed, Missle': '2',
    'Speed, Melee': '3',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '3',
    'STN, 2H': '2',
    STMOD: '0.4',
    'CDN, 1H': '6',
    'CDN, 2H': '4.5',
    CDMOD: '0.4',
    'Damage Dice': '2d4+9',
    'Dividing Die': '10',
    'Real min': '1.10',
    'Max Dam': '17',
    'Av Dam': '9.05',
  },
  {
    KEY: 'DAGGERS_CLAWS (MARTIAL)',
    Name: 'Claws (martial)',
    'Cost ep': '80',
    Weight: '15',
    Size: '12',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '1',
    'Speed, Readied': '1',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '4',
    'STN, 2H': '3',
    STMOD: '0.5',
    'CDN, 1H': '7',
    'CDN, 2H': '5.25',
    CDMOD: '0.6',
    'Damage Dice': '1d8+9',
    'Dividing Die': '8',
    'Real min': '1.25',
    'Max Dam': '17',
    'Av Dam': '9.13',
  },
  {
    KEY: 'DAGGERS_RONDEL (EASTERN)',
    Name: 'Rondel (Eastern)',
    'Cost ep': '40',
    Weight: '40',
    Size: '20',
    Range: '5',
    'Speed, Missle': '3',
    'Speed, Melee': '3',
    'Speed, Readied': '1',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '6',
    'STN, 2H': '4.5',
    STMOD: '.55',
    'CDN, 1H': '7',
    'CDN, 2H': '5.25',
    CDMOD: '.55',
    'Damage Dice': '2d4+9',
    'Dividing Die': '8',
    'Real min': '1.38',
    'Max Dam': '17',
    'Av Dam': '3.11',
  },
  {
    KEY: 'DAGGERS_HAND LUNE (MARTIAL)',
    Name: 'Hand Lune (martial)',
    'Cost ep': '60',
    Weight: '35',
    Size: '15',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '3',
    'Speed, Readied': '3',
    Protection: '2',
    'Threat Range': '-1',
    'STN, 1H': '7',
    'STN, 2H': '5.25',
    STMOD: '0.8',
    'CDN, 1H': '8',
    'CDN, 2H': '6',
    CDMOD: '0.5',
    'Damage Dice': '1d8+9',
    'Dividing Die': '8',
    'Real min': '1.25',
    'Max Dam': '17',
    'Av Dam': '9.13',
  },
  {
    KEY: 'DAGGERS_BANK',
    Name: 'Bank',
    'Cost ep': '30',
    Weight: '16',
    Size: '10',
    Range: '2',
    'Speed, Missle': '5',
    'Speed, Melee': '3',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '4',
    'STN, 2H': '3',
    STMOD: '0.5',
    'CDN, 1H': '5',
    'CDN, 2H': '3.74',
    CDMOD: '0.32',
    'Damage Dice': '1d8+10',
    'Dividing Die': '10',
    'Real min': '1.10',
    'Max Dam': '18',
    'Av Dam': '9.55',
  },
  {
    KEY: 'DAGGERS_KUKRI',
    Name: 'Kukri',
    'Cost ep': '60',
    Weight: '25',
    Size: '13',
    Range: '15',
    'Speed, Missle': '2',
    'Speed, Melee': '3',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '6',
    'STN, 2H': '4.5',
    STMOD: '0.78',
    'CDN, 1H': '9',
    'CDN, 2H': '6.75',
    CDMOD: '0.6',
    'Damage Dice': '1d8+10',
    'Dividing Die': '8',
    'Real min': '1.38',
    'Max Dam': '18',
    'Av Dam': '9.69',
  },
  {
    KEY: 'DAGGERS_HOBTASKULIS (LONGCLAW, MARTIAL)',
    Name: 'Hobtaskulis (longclaw, martial)',
    'Cost ep': '100',
    Weight: '30',
    Size: '20',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '2',
    'Speed, Readied': '1',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '6',
    'STN, 2H': '0',
    STMOD: '0.6',
    'CDN, 1H': '10',
    'CDN, 2H': '0',
    CDMOD: '0.9',
    'Damage Dice': '2d4+10',
    'Dividing Die': '8',
    'Real min': '1.50',
    'Max Dam': '18',
    'Av Dam': '9.75',
  },
  {
    KEY: 'DAGGERS_KATAR (PUNCH DAGGER)',
    Name: 'Katar (punch dagger)',
    'Cost ep': '60',
    Weight: '30',
    Size: '9',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '2',
    'Speed, Readied': '1',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '5',
    'STN, 2H': '3.75',
    STMOD: '0.6',
    'CDN, 1H': '6',
    'CDN, 2H': '4.5',
    CDMOD: '0.52',
    'Damage Dice': '1d6+1d4+9',
    'Dividing Die': '8',
    'Real min': '1.38',
    'Max Dam': '19',
    'Av Dam': '10.19',
  },
  {
    KEY: 'DAGGERS_SAX',
    Name: 'Sax',
    'Cost ep': '50',
    Weight: '30',
    Size: '18',
    Range: '4',
    'Speed, Missle': '4',
    'Speed, Melee': '4',
    'Speed, Readied': '4',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '6',
    'STN, 2H': '4.5',
    STMOD: '0.85',
    'CDN, 1H': '6',
    'CDN, 2H': '4.5',
    CDMOD: '0.45',
    'Damage Dice': '1d10+12',
    'Dividing Die': '8',
    'Real min': '1.63',
    'Max Dam': '22',
    'Av Dam': '11.81',
  },
];

let DRESS_SWORDS_ITEMS = [
  {
    KEY: 'DRESS_SWORDS_SWORD CANE',
    Name: 'Sword Cane',
    'Cost ep': '150',
    Weight: '30',
    Size: '31',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '5',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '13',
    'STN, 2H': '9.75',
    STMOD: '2.1',
    'CDN, 1H': '14',
    'CDN, 2H': '10.5',
    CDMOD: '1',
    'Damage Dice': '2d4+8',
    'Dividing Die': '8',
    'Real min': '1.25',
    'Max Dam': '16',
    'Av Dam': '8.63',
  },
  {
    KEY: 'DRESS_SWORDS_FOIL',
    Name: 'Foil',
    'Cost ep': '80',
    Weight: '20',
    Size: '36',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '4',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '9',
    'STN, 2H': '6.75',
    STMOD: '1.3',
    'CDN, 1H': '15',
    'CDN, 2H': '11.25',
    CDMOD: '1.2',
    'Damage Dice': '1d12+5',
    'Dividing Die': '8',
    'Real min': '0.75',
    'Max Dam': '17',
    'Av Dam': '8.88',
  },
  {
    KEY: 'DRESS_SWORDS_EPEE',
    Name: 'Epee',
    'Cost ep': '110',
    Weight: '25',
    Size: '48',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '3',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '12',
    'STN, 2H': '9',
    STMOD: '1.8',
    'CDN, 1H': '15',
    'CDN, 2H': '11.25',
    CDMOD: '1.2',
    'Damage Dice': '1d10+11',
    'Dividing Die': '8',
    'Real min': '1.50',
    'Max Dam': '21',
    'Av Dam': '11.25',
  },
  {
    KEY: 'DRESS_SWORDS_RAPIER',
    Name: 'Rapier',
    'Cost ep': '200',
    Weight: '40',
    Size: '40',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '3',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '12',
    'STN, 2H': '9',
    STMOD: '1.8',
    'CDN, 1H': '16',
    'CDN, 2H': '12',
    CDMOD: '1.4',
    'Damage Dice': '2d4+1d8+10',
    'Dividing Die': '6',
    'Real min': '2.17',
    'Max Dam': '26',
    'Av Dam': '14.08',
  },
];

let POLE_ARMS_ITEMS = [
  {
    KEY: 'POLE_ARMS_QUARTERSTAFF',
    Name: 'Quarterstaff',
    'Cost ep': '30',
    Weight: '40',
    Size: '48',
    Range: '4',
    'Speed, Missle': '8',
    'Speed, Melee': '4',
    'Speed, Readied': '4',
    Protection: '3',
    'Threat Range': '-2',
    'STN, 1H': '6',
    'STN, 2H': '4.5',
    STMOD: '0.75',
    'CDN, 1H': '12',
    'CDN, 2H': '9',
    CDMOD: '0.85',
    'Damage Dice': '1d8+10',
    'Dividing Die': '8',
    'Real min': '1.38',
    'Max Dam': '18',
    'Av Dam': '9.69',
  },
  {
    KEY: 'POLE_ARMS_FAUCHARD',
    Name: 'Fauchard',
    'Cost ep': '180',
    Weight: '200',
    Size: '96',
    Range: '10',
    'Speed, Missle': '6',
    'Speed, Melee': '8',
    'Speed, Readied': '8',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '15',
    'STN, 2H': '11',
    STMOD: '2.1',
    'CDN, 1H': '13',
    'CDN, 2H': '10',
    CDMOD: '0.65',
    'Damage Dice': '1d10+12',
    'Dividing Die': '6',
    'Real min': '2.17',
    'Max Dam': '22',
    'Av Dam': '12.08',
  },
  {
    KEY: 'POLE_ARMS_VOULGE',
    Name: 'Voulge',
    'Cost ep': '150',
    Weight: '150',
    Size: '96',
    Range: '10',
    'Speed, Missle': '7',
    'Speed, Melee': '6',
    'Speed, Readied': '5',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '14',
    'STN, 2H': '10.5',
    STMOD: '2',
    'CDN, 1H': '16',
    'CDN, 2H': '12',
    CDMOD: '0.9',
    'Damage Dice': '1d10+15',
    'Dividing Die': '6',
    'Real min': '2.67',
    'Max Dam': '25',
    'Av Dam': '13.83',
  },
  {
    KEY: 'POLE_ARMS_BILL HOOK',
    Name: 'Bill Hook',
    'Cost ep': '130',
    Weight: '190',
    Size: '112',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '7',
    'Speed, Readied': '7',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '18',
    'STN, 2H': '13.5',
    STMOD: '2.55',
    'CDN, 1H': '18',
    'CDN, 2H': '13.5',
    CDMOD: '0.7',
    'Damage Dice': '1d12+17',
    'Dividing Die': '5',
    'Real min': '3.60',
    'Max Dam': '29',
    'Av Dam': '16.30',
  },
  {
    KEY: 'POLE_ARMS_DEMI-LUNE',
    Name: 'Demi-Lune',
    'Cost ep': '180',
    Weight: '150',
    Size: '140',
    Range: '20',
    'Speed, Missle': '10',
    'Speed, Melee': '9',
    'Speed, Readied': '8',
    Protection: '2',
    'Threat Range': '-1',
    'STN, 1H': '15',
    'STN, 2H': '11.25',
    STMOD: '2.1',
    'CDN, 1H': '19',
    'CDN, 2H': '14.25',
    CDMOD: '0.9',
    'Damage Dice': '1d12+17',
    'Dividing Die': '5',
    'Real min': '3.60',
    'Max Dam': '29',
    'Av Dam': '16.30',
  },
  {
    KEY: 'POLE_ARMS_HALBARD',
    Name: 'Halbard',
    'Cost ep': '220',
    Weight: '250',
    Size: '98',
    Range: '5',
    'Speed, Missle': '10',
    'Speed, Melee': '9',
    'Speed, Readied': '6',
    Protection: '1',
    'Threat Range': '0',
    'STN, 1H': '18',
    'STN, 2H': '13.5',
    STMOD: '2.55',
    'CDN, 1H': '17',
    'CDN, 2H': '12.5',
    CDMOD: '0.85',
    'Damage Dice': '1d12+18',
    'Dividing Die': '5',
    'Real min': '3.80',
    'Max Dam': '30',
    'Av Dam': '16.90',
  },
  {
    KEY: 'POLE_ARMS_CHAUVIS SAURIS',
    Name: 'Chauvis Sauris',
    'Cost ep': '500',
    Weight: '190',
    Size: '144',
    Range: '5',
    'Speed, Missle': '7',
    'Speed, Melee': '10',
    'Speed, Readied': '9',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '20',
    'STN, 2H': '15',
    STMOD: '2.8',
    'CDN, 1H': '17',
    'CDN, 2H': '12.5',
    CDMOD: '0.9',
    'Damage Dice': '1d8+1d6+19',
    'Dividing Die': '5',
    'Real min': '4.20',
    'Max Dam': '33',
    'Av Dam': '18.60',
  },
  {
    KEY: 'POLE_ARMS_POLE AXE',
    Name: 'Pole Axe',
    'Cost ep': '420',
    Weight: '340',
    Size: '133',
    Range: '3',
    'Speed, Missle': '10',
    'Speed, Melee': '13',
    'Speed, Readied': '11',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '19',
    'STN, 2H': '14',
    STMOD: '2.66',
    'CDN, 1H': '17',
    'CDN, 2H': '12.75',
    CDMOD: '0.85',
    'Damage Dice': '3d6+22',
    'Dividing Die': '4',
    'Real min': '6.25',
    'Max Dam': '40',
    'Av Dam': '23.13',
  },
];

let STRAIGHT_SWORDS_ITEMS = [
  {
    KEY: 'STRAIGHT_SWORDS_QUARTERSTAFF',
    Name: 'Quarterstaff',
    'Cost ep': '30',
    Weight: '40',
    Size: '48',
    Range: '4',
    'Speed, Missle': '8',
    'Speed, Melee': '4',
    'Speed, Readied': '4',
    Protection: '3',
    'Threat Range': '-2',
    'STN, 1H': '6',
    'STN, 2H': '4.5',
    STMOD: '0.75',
    'CDN, 1H': '12',
    'CDN, 2H': '9',
    CDMOD: '0.85',
    'Damage Dice': '1d8+10',
    'Dividing Die': '8',
    'Real min': '1.38',
    'Max Dam': '18',
    'Av Dam': '9.69',
  },
  {
    KEY: 'STRAIGHT_SWORDS_SHORT SWORD',
    Name: 'Short Sword',
    'Cost ep': '44',
    Weight: '35',
    Size: '24',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '4',
    'Speed, Readied': '4',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '11',
    'STN, 2H': '8.25',
    STMOD: '1.75',
    'CDN, 1H': '10',
    'CDN, 2H': '7.5',
    CDMOD: '0.75',
    'Damage Dice': '1d10+12',
    'Dividing Die': '8',
    'Real min': '1.63',
    'Max Dam': '22',
    'Av Dam': '11.81',
  },
  {
    KEY: 'STRAIGHT_SWORDS_PATAR',
    Name: 'Patar',
    'Cost ep': '180',
    Weight: '120',
    Size: '36',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '7',
    'Speed, Readied': '7',
    Protection: '4',
    'Threat Range': '-2',
    'STN, 1H': '14',
    'STN, 2H': '10.5',
    STMOD: '2.1',
    'CDN, 1H': '15',
    'CDN, 2H': '11.25',
    CDMOD: '1.2',
    'Damage Dice': '2d6+10',
    'Dividing Die': '6',
    'Real min': '2.00',
    'Max Dam': '22',
    'Av Dam': '12.00',
  },
  {
    KEY: 'STRAIGHT_SWORDS_GLADIUS',
    Name: 'Gladius',
    'Cost ep': '80',
    Weight: '70',
    Size: '30',
    Range: '3',
    'Speed, Missle': '6',
    'Speed, Melee': '4',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '13',
    'STN, 2H': '9.75',
    STMOD: '2.1',
    'CDN, 1H': '13',
    'CDN, 2H': '9.75',
    CDMOD: '0.95',
    'Damage Dice': '2d6+14',
    'Dividing Die': '8',
    'Real min': '2.00',
    'Max Dam': '26',
    'Av Dam': '14.00',
  },
  {
    KEY: 'STRAIGHT_SWORDS_BROADSWORD',
    Name: 'Broadsword',
    'Cost ep': '100',
    Weight: '130',
    Size: '44',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '5',
    'Speed, Readied': '5',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '15',
    'STN, 2H': '11.25',
    STMOD: '2.4',
    'CDN, 1H': '16',
    'CDN, 2H': '12',
    CDMOD: '1.15',
    'Damage Dice': '1d10+16',
    'Dividing Die': '6',
    'Real min': '2.83',
    'Max Dam': '26',
    'Av Dam': '14.42',
  },
  {
    KEY: 'STRAIGHT_SWORDS_BASTARD SWORD',
    Name: 'Bastard Sword',
    'Cost ep': '350',
    Weight: '150',
    Size: '55',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '6',
    'Speed, Readied': '6',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '17',
    'STN, 2H': '12.75',
    STMOD: '2.75',
    'CDN, 1H': '18',
    'CDN, 2H': '13.5',
    CDMOD: '1.3',
    'Damage Dice': '1d8+1d6+16',
    'Dividing Die': '6',
    'Real min': '3.00',
    'Max Dam': '30',
    'Av Dam': '16.50',
  },
  {
    KEY: 'STRAIGHT_SWORDS_GREAT SWORD/CLAYMORE',
    Name: 'Great Sword/Claymore',
    'Cost ep': '240',
    Weight: '190',
    Size: '70',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '10',
    'Speed, Readied': '10',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '21',
    'STN, 2H': '15.75',
    STMOD: '3.35',
    'CDN, 1H': '19',
    'CDN, 2H': '14.25',
    CDMOD: '1.5',
    'Damage Dice': '1d8+1d10+13',
    'Dividing Die': '5',
    'Real min': '3.00',
    'Max Dam': '31',
    'Av Dam': '17.00',
  },
  {
    KEY: 'STRAIGHT_SWORDS_TWO HANDED SWORD',
    Name: 'Two Handed Sword',
    'Cost ep': '260',
    Weight: '170',
    Size: '64',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '10',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '20',
    'STN, 2H': '15',
    STMOD: '3.2',
    'CDN, 1H': '19',
    'CDN, 2H': '14.25',
    CDMOD: '1.36',
    'Damage Dice': '2d8+17',
    'Dividing Die': '5',
    'Real min': '3.80',
    'Max Dam': '33',
    'Av Dam': '18.40',
  },
  {
    KEY: 'STRAIGHT_SWORDS_FLAMEBERGE',
    Name: 'Flameberge',
    'Cost ep': '380',
    Weight: '170',
    Size: '75',
    Range: '0',
    'Speed, Missle': '0',
    'Speed, Melee': '11',
    'Speed, Readied': '11',
    Protection: '0',
    'Threat Range': '1',
    'STN, 1H': '22',
    'STN, 2H': '16.5',
    STMOD: '3.3',
    'CDN, 1H': '20',
    'CDN, 2H': '15',
    CDMOD: '1',
    'Damage Dice': '3d6+15',
    'Dividing Die': '4',
    'Real min': '4.50',
    'Max Dam': '33',
    'Av Dam': '18.75',
  },
];

let SPEARS_ITEMS = [
  {
    KEY: 'SPEARS_QUARTERSTAFF',
    Name: 'Quarterstaff',
    'Cost ep': '30',
    Weight: '40',
    Size: '48',
    Range: '4',
    'Speed, Missle': '8',
    'Speed, Melee': '4',
    'Speed, Readied': '4',
    Protection: '3',
    'Threat Range': '-2',
    'STN, 1H': '6',
    'STN, 2H': '4.5',
    STMOD: '0.75',
    'CDN, 1H': '12',
    'CDN, 2H': '9',
    CDMOD: '0.85',
    'Damage Dice': '1d8+10',
    'Dividing Die': '8',
    'Real min': '1.38',
    'Max Dam': '18',
    'Av Dam': '9.69',
  },
  {
    KEY: "SPEARS_HUD'JU",
    Name: "Hud'ju",
    'Cost ep': '50',
    Weight: '35',
    Size: '33',
    Range: '25',
    'Speed, Missle': '3',
    'Speed, Melee': '3',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '5',
    'STN, 2H': '3.5',
    STMOD: '0.7',
    'CDN, 1H': '8',
    'CDN, 2H': '6',
    CDMOD: '0.5',
    'Damage Dice': '1d6+11',
    'Dividing Die': '8',
    'Real min': '1.50',
    'Max Dam': '17',
    'Av Dam': '9.25',
  },
  {
    KEY: 'SPEARS_COMMON SPEAR',
    Name: 'Common Spear',
    'Cost ep': '20',
    Weight: '50',
    Size: '37',
    Range: '30',
    'Speed, Missle': '4',
    'Speed, Melee': '4',
    'Speed, Readied': '4',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '5',
    'STN, 2H': '3.75',
    STMOD: '0.7',
    'CDN, 1H': '6',
    'CDN, 2H': '4.5',
    CDMOD: '0.33',
    'Damage Dice': '1d6+12',
    'Dividing Die': '8',
    'Real min': '1.63',
    'Max Dam': '18',
    'Av Dam': '9.81',
  },
  {
    KEY: "SPEARS_SERIHUD'JU",
    Name: "serihud'ju",
    'Cost ep': '70',
    Weight: '40',
    Size: '32',
    Range: '20',
    'Speed, Missle': '3',
    'Speed, Melee': '3',
    'Speed, Readied': '2',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '6',
    'STN, 2H': '4.3',
    STMOD: '0.75',
    'CDN, 1H': '8',
    'CDN, 2H': '6',
    CDMOD: '0.5',
    'Damage Dice': '1d8+11',
    'Dividing Die': '6',
    'Real min': '2.00',
    'Max Dam': '19',
    'Av Dam': '10.50',
  },
  {
    KEY: 'SPEARS_ASSEGAI',
    Name: 'Assegai',
    'Cost ep': '140',
    Weight: '60',
    Size: '35',
    Range: '50',
    'Speed, Missle': '4',
    'Speed, Melee': '4',
    'Speed, Readied': '3',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '6',
    'STN, 2H': '4.5',
    STMOD: '0.5',
    'CDN, 1H': '12',
    'CDN, 2H': '9',
    CDMOD: '0.72',
    'Damage Dice': '1d8+12',
    'Dividing Die': '6',
    'Real min': '2.17',
    'Max Dam': '20',
    'Av Dam': '11.08',
  },
  {
    KEY: 'SPEARS_HOKO (WAR RAKE)',
    Name: 'Hoko (war Rake)',
    'Cost ep': '60',
    Weight: '90',
    Size: '70',
    Range: '3',
    'Speed, Missle': '10',
    'Speed, Melee': '7',
    'Speed, Readied': '7',
    Protection: '1',
    'Threat Range': '-2',
    'STN, 1H': '12',
    'STN, 2H': '9',
    STMOD: '1.7',
    'CDN, 1H': '14',
    'CDN, 2H': '10',
    CDMOD: '1.1',
    'Damage Dice': '1d10+12',
    'Dividing Die': '6',
    'Real min': '2.17',
    'Max Dam': '22',
    'Av Dam': '12.08',
  },
  {
    KEY: 'SPEARS_TRIDENT',
    Name: 'Trident',
    'Cost ep': '140',
    Weight: '120',
    Size: '62',
    Range: '20',
    'Speed, Missle': '6',
    'Speed, Melee': '7',
    'Speed, Readied': '6',
    Protection: '1',
    'Threat Range': '1',
    'STN, 1H': '11',
    'STN, 2H': '8',
    STMOD: '1.55',
    'CDN, 1H': '11',
    'CDN, 2H': '8.25',
    CDMOD: '0.75',
    'Damage Dice': '1d12+16',
    'Dividing Die': '6',
    'Real min': '2.83',
    'Max Dam': '28',
    'Av Dam': '15.42',
  },
  {
    KEY: 'SPEARS_PILUM',
    Name: 'Pilum',
    'Cost ep': '150',
    Weight: '100',
    Size: '60',
    Range: '30',
    'Speed, Missle': '5',
    'Speed, Melee': '5',
    'Speed, Readied': '4',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '14',
    'STN, 2H': '10.5',
    STMOD: '2',
    'CDN, 1H': '10',
    'CDN, 2H': '8',
    CDMOD: '0.7',
    'Damage Dice': '1d12+17',
    'Dividing Die': '6',
    'Real min': '3.00',
    'Max Dam': '29',
    'Av Dam': '16.00',
  },
  {
    KEY: 'SPEARS_MEDIEVAL LANCE',
    Name: 'Medieval Lance',
    'Cost ep': '240',
    Weight: '220',
    Size: '108',
    Range: '10',
    'Speed, Missle': '10',
    'Speed, Melee': '6',
    'Speed, Readied': '5',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '17',
    'STN, 2H': '12.75',
    STMOD: '2.3',
    'CDN, 1H': '15',
    'CDN, 2H': '11',
    CDMOD: '1.5',
    'Damage Dice': '3d8+19',
    'Dividing Die': '5',
    'Real min': '4.40',
    'Max Dam': '43',
    'Av Dam': '23.70',
  },
];

let THROWN_ITEMS = [
  {
    KEY: 'THROWN_QUARTERSTAFF',
    Name: 'Quarterstaff',
    'Cost ep': '30',
    Weight: '40',
    Size: '48',
    Range: '4',
    'Speed, Missle': '8',
    'Speed, Melee': '4',
    'Speed, Readied': '4',
    Protection: '3',
    'Threat Range': '-2',
    'STN, 1H': '6',
    'STN, 2H': '4.5',
    STMOD: '0.75',
    'CDN, 1H': '12',
    'CDN, 2H': '9',
    CDMOD: '0.85',
    'Damage Dice': '1d8+10',
    'Dividing Die': '8',
    'Real min': '1.38',
    'Max Dam': '18',
    'Av Dam': '9.69',
  },
  {
    KEY: 'THROWN_SMALL LEAD SHOT',
    Name: 'small lead shot',
    'Cost ep': '.2',
    Weight: '2',
    Size: '1',
    Range: ' ',
    'Speed, Missle': ' ',
    'Speed, Melee': ' ',
    'Speed, Readied': ' ',
    Protection: ' ',
    'Threat Range': '-1',
    'STN, 1H': ' ',
    'STN, 2H': ' ',
    STMOD: ' ',
    'CDN, 1H': ' ',
    'CDN, 2H': ' ',
    CDMOD: ' ',
    'Damage Dice': '2d4+9',
    'Dividing Die': '10',
    'Real min': '1.7',
    'Max Dam': '17',
    'Av Dam': ' ',
  },
  {
    KEY: 'THROWN_LEAD BALL',
    Name: 'Lead Ball',
    'Cost ep': '1',
    Weight: '35',
    Size: '2',
    Range: '10',
    'Speed, Missle': '2',
    'Speed, Melee': '0',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '12',
    'STN, 2H': '9',
    STMOD: '1',
    'CDN, 1H': '12',
    'CDN, 2H': '9',
    CDMOD: '1.7',
    'Damage Dice': '1d6+1d4+2',
    'Dividing Die': '10',
    'Real min': '0.40',
    'Max Dam': '12',
    'Av Dam': '6.20',
  },
  {
    KEY: 'THROWN_SHURIKEN',
    Name: 'Shuriken',
    'Cost ep': '20',
    Weight: '5',
    Size: '3',
    Range: '25',
    'Speed, Missle': '2',
    'Speed, Melee': '0',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '4',
    'STN, 2H': '3',
    STMOD: '0.4',
    'CDN, 1H': '13',
    'CDN, 2H': '9.5',
    CDMOD: '2',
    'Damage Dice': '1d6+1d4+3',
    'Dividing Die': '8',
    'Real min': '0.63',
    'Max Dam': '13',
    'Av Dam': '6.81',
  },
  {
    KEY: 'THROWN_CHAKRAM',
    Name: 'Chakram',
    'Cost ep': '100',
    Weight: '25',
    Size: '12',
    Range: '35',
    'Speed, Missle': '4',
    'Speed, Melee': '9',
    'Speed, Readied': '4',
    Protection: '0',
    'Threat Range': '-1',
    'STN, 1H': '10',
    'STN, 2H': '7.5',
    STMOD: '0.9',
    'CDN, 1H': '15',
    'CDN, 2H': '11.25',
    CDMOD: '1.8',
    'Damage Dice': '2d6+10',
    'Dividing Die': '8',
    'Real min': '1.50',
    'Max Dam': '22',
    'Av Dam': '11.75',
  },
  {
    KEY: 'THROWN_SLING',
    Name: 'Sling',
    'Cost ep': '8',
    Weight: '12',
    Size: '5',
    Range: '50',
    'Speed, Missle': '3',
    'Speed, Melee': '0',
    'Speed, Readied': '0',
    Protection: '0',
    'Threat Range': '0',
    'STN, 1H': '6',
    'STN, 2H': '6',
    STMOD: '.4',
    'CDN, 1H': '11',
    'CDN, 2H': '8.25',
    CDMOD: '1.6',
    'Damage Dice': '+22',
    'Dividing Die': ' ',
    'Real min': ' ',
    'Max Dam': ' ',
    'Av Dam': ' ',
  },
];

let ALL_WEAPONS_ARRAYS = [
  { type: 'AXES', items: AXES_ITEMS },
  { type: 'BLUNT', items: BLUNT_ITEMS },
  { type: 'BOWS', items: BOWS_ITEMS },
  { type: 'CROSSBOWS', items: CROSSBOWS_ITEMS },
  { type: 'ARROWS', items: ARROWS_ITEMS },
  { type: 'CURVED_SWORDS', items: CURVED_SWORDS_ITEMS },
  { type: 'DAGGERS', items: DAGGERS_ITEMS },
  { type: 'DRESS_SWORDS', items: DRESS_SWORDS_ITEMS },
  { type: 'POLE_ARMS', items: POLE_ARMS_ITEMS },
  { type: 'SPEARS', items: SPEARS_ITEMS },
  { type: 'STRAIGHT_SWORDS', items: STRAIGHT_SWORDS_ITEMS },
  { type: 'THROWN', items: THROWN_ITEMS },
];

// create both a master list and a lookup table for the items
// the item lookup table (by key)
let weaponLookup = {};
let itemLookup = {};
let allWeapons = [];
let weaponTypes = [];
ALL_WEAPONS_ARRAYS.forEach(function (weapon_array) {
  weaponTypes.push(weapon_array.type);
  weapon_array.items.forEach(function (item) {
    item['CATEGORY'] = 'WEAPON';
    item['TYPE'] = weapon_array.type;
    weaponLookup[item['KEY']] = item;
    allWeapons.push(item);
    // add to the general item hash and armors array
    itemLookup[item['KEY']] = item;
  });
});

let ARMOR_SETS_ITEMS = [
  {
    KEY: 'ARMOR_CHICKEN SKIN ARMOR',
    'Armor Type': 'Chicken Skin Armor',
    Classification: 'Garment, Leather',
    'approx weight': '175',
    'approx cost ELP': '3',
    commonality: '50',
    'Base AV': '15',
    'Base PR': '7',
  },
  {
    KEY: 'ARMOR_BASIC SILK',
    'Armor Type': 'Basic Silk',
    Classification: 'Garment, fabric',
    'approx weight': '125',
    'approx cost ELP': '40',
    commonality: '95',
    'Base AV': '5',
    'Base PR': '5',
  },
  {
    KEY: 'ARMOR_QUILTED SILK',
    'Armor Type': 'Quilted Silk',
    Classification: 'Garment, fabric',
    'approx weight': '190',
    'approx cost ELP': '40',
    commonality: '92',
    'Base AV': '8',
    'Base PR': '7',
  },
  {
    KEY: 'ARMOR_PADDED SILK',
    'Armor Type': 'Padded Silk',
    Classification: 'Garment, fabric',
    'approx weight': '170',
    'approx cost ELP': '50',
    commonality: '90',
    'Base AV': '10',
    'Base PR': '10',
  },
  {
    KEY: 'ARMOR_SFT LEATHER ARMOR',
    'Armor Type': 'Sft Leather Armor',
    Classification: 'Garment, Leather',
    'approx weight': '160',
    'approx cost ELP': '80',
    commonality: '95',
    'Base AV': '12',
    'Base PR': '13',
  },
  {
    KEY: 'ARMOR_HARDENED LEATHER',
    'Armor Type': 'Hardened Leather',
    Classification: 'Segmented, unbacked',
    'approx weight': '200',
    'approx cost ELP': '100',
    commonality: '90',
    'Base AV': '17',
    'Base PR': '16',
  },
  {
    KEY: 'ARMOR_STUDDED HARDENED LEATHER',
    'Armor Type': 'Studded Hardened Leather',
    Classification: 'Segmented, unbacked',
    'approx weight': '210',
    'approx cost ELP': '140',
    commonality: '88',
    'Base AV': '20',
    'Base PR': '18',
  },
  {
    KEY: 'ARMOR_RINGED LEATHER',
    'Armor Type': 'Ringed Leather',
    Classification: 'Segmented, backed',
    'approx weight': '230',
    'approx cost ELP': '165',
    commonality: '80',
    'Base AV': '23',
    'Base PR': '19',
  },
  {
    KEY: 'ARMOR_CHAIN LEATHER',
    'Armor Type': 'Chain Leather',
    Classification: 'Segmented, backed',
    'approx weight': '230',
    'approx cost ELP': '190',
    commonality: '75',
    'Base AV': '22',
    'Base PR': '19',
  },
  {
    KEY: 'ARMOR_RING MAIL',
    'Armor Type': 'Ring Mail',
    Classification: 'Maille',
    'approx weight': '270',
    'approx cost ELP': '260',
    commonality: '86',
    'Base AV': '32',
    'Base PR': '20',
  },
  {
    KEY: 'ARMOR_SCALE MAIL',
    'Armor Type': 'Scale Mail',
    Classification: 'Maille',
    'approx weight': '250',
    'approx cost ELP': '270',
    commonality: '86',
    'Base AV': '32',
    'Base PR': '21',
  },
  {
    KEY: 'ARMOR_CHAIN MAIL',
    'Armor Type': 'Chain Mail',
    Classification: 'Maille',
    'approx weight': '240',
    'approx cost ELP': '450',
    commonality: '81',
    'Base AV': '35',
    'Base PR': '22',
  },
  {
    KEY: 'ARMOR_SPLINTED MAIL',
    'Armor Type': 'Splinted Mail',
    Classification: 'Maille',
    'approx weight': '265',
    'approx cost ELP': '550',
    commonality: '80',
    'Base AV': '38',
    'Base PR': '24',
  },
  {
    KEY: 'ARMOR_BANDED MAIL',
    'Armor Type': 'Banded Mail',
    Classification: 'Maille',
    'approx weight': '275',
    'approx cost ELP': '570',
    commonality: '77',
    'Base AV': '40',
    'Base PR': '25',
  },
  {
    KEY: 'ARMOR_PLATED MAIL',
    'Armor Type': 'Plated Mail',
    Classification: 'Maille',
    'approx weight': '320',
    'approx cost ELP': '650',
    commonality: '70',
    'Base AV': '43',
    'Base PR': '27',
  },
  {
    KEY: 'ARMOR_RING ARMOR',
    'Armor Type': 'Ring Armor',
    Classification: 'Segmented, backed',
    'approx weight': '310',
    'approx cost ELP': '970',
    commonality: '75',
    'Base AV': '46',
    'Base PR': '29',
  },
  {
    KEY: 'ARMOR_SCALE ARMOR',
    'Armor Type': 'Scale Armor',
    Classification: 'Segmented, backed',
    'approx weight': '300',
    'approx cost ELP': '1050',
    commonality: '72',
    'Base AV': '51',
    'Base PR': '33',
  },
  {
    KEY: 'ARMOR_CHAIN ARMOR',
    'Armor Type': 'Chain Armor',
    Classification: 'Segmented, backed',
    'approx weight': '280',
    'approx cost ELP': '1480',
    commonality: '68',
    'Base AV': '50',
    'Base PR': '35',
  },
  {
    KEY: 'ARMOR_SPLINT ARMOR',
    'Armor Type': 'Splint Armor',
    Classification: 'Segmented, backed',
    'approx weight': '380',
    'approx cost ELP': '1650',
    commonality: '65',
    'Base AV': '52',
    'Base PR': '39',
  },
  {
    KEY: 'ARMOR_LORICA SEGMENTATA (BANDED ARMOR)',
    'Armor Type': 'Lorica segmentata (banded armor)',
    Classification: 'Segmented, backed',
    'approx weight': '300',
    'approx cost ELP': '1800',
    commonality: '60',
    'Base AV': '54',
    'Base PR': '41',
  },
  {
    KEY: 'ARMOR_LAMMELLAR',
    'Armor Type': 'Lammellar',
    Classification: 'Segmented, unbacked',
    'approx weight': '470',
    'approx cost ELP': '2400',
    commonality: '55',
    'Base AV': '56',
    'Base PR': '44',
  },
  {
    KEY: 'ARMOR_PLATE ARMOR',
    'Armor Type': 'Plate Armor',
    Classification: 'Plate',
    'approx weight': '505',
    'approx cost ELP': '3100',
    commonality: '59',
    'Base AV': '58',
    'Base PR': '46',
  },
  {
    KEY: 'ARMOR_FIELD PLATE  (COAT OF PLATES)',
    'Armor Type': 'Field Plate  (coat of plates)',
    Classification: 'Plate',
    'approx weight': '475',
    'approx cost ELP': '4200',
    commonality: '40',
    'Base AV': '60',
    'Base PR': '50',
  },
];

let allArmors = [];
ARMOR_SETS_ITEMS.forEach(function (item) {
  item['CATEGORY'] = 'ARMOR';
  item['TYPE'] = 'ARMOR SET';
  // add to the general item hash and armors array
  itemLookup[item['KEY']] = item;
  allArmors.push(item);
});

// a list of proerties subject to modification by others for weapons, armors, and spells
let weaponModifiers = [];
let armorModifiers = [];
let spellModifiers = [];

export const WEAPON_LOOKUP = weaponLookup;
export const WEAPON_TYPES = weaponTypes;
export const ALL_WEAPONS = allWeapons;
export const ALL_ARMORS = allArmors;
export const ITEM_LOOKUP = itemLookup;
